//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class CheckIfRobotStateExistsInWarehouseResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/CheckIfRobotStateExistsInWarehouse";

        public bool exists;

        public CheckIfRobotStateExistsInWarehouseResponse()
        {
            this.exists = false;
        }

        public CheckIfRobotStateExistsInWarehouseResponse(bool exists)
        {
            this.exists = exists;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.exists));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.exists = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "CheckIfRobotStateExistsInWarehouseResponse: " +
            "\nexists: " + exists.ToString();
        }
    }
}
