//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetMotionPlanResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetMotionPlan";

        public MotionPlanResponse motion_plan_response;

        public GetMotionPlanResponse()
        {
            this.motion_plan_response = new MotionPlanResponse();
        }

        public GetMotionPlanResponse(MotionPlanResponse motion_plan_response)
        {
            this.motion_plan_response = motion_plan_response;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(motion_plan_response.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.motion_plan_response.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetMotionPlanResponse: " +
            "\nmotion_plan_response: " + motion_plan_response.ToString();
        }
    }
}
