//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetMotionSequenceResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetMotionSequence";

        //  Response to the planning request
        public MotionSequenceResponse response;

        public GetMotionSequenceResponse()
        {
            this.response = new MotionSequenceResponse();
        }

        public GetMotionSequenceResponse(MotionSequenceResponse response)
        {
            this.response = response;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(response.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.response.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetMotionSequenceResponse: " +
            "\nresponse: " + response.ToString();
        }
    }
}
