//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetMotionPlanRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetMotionPlan";

        //  This service contains the definition for a request to the motion
        //  planner and the output it provides
        public MotionPlanRequest motion_plan_request;

        public GetMotionPlanRequest()
        {
            this.motion_plan_request = new MotionPlanRequest();
        }

        public GetMotionPlanRequest(MotionPlanRequest motion_plan_request)
        {
            this.motion_plan_request = motion_plan_request;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(motion_plan_request.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.motion_plan_request.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetMotionPlanRequest: " +
            "\nmotion_plan_request: " + motion_plan_request.ToString();
        }
    }
}
