//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetMotionSequenceRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetMotionSequence";

        //  Planning request with a list of motion commands
        public MotionSequenceRequest request;

        public GetMotionSequenceRequest()
        {
            this.request = new MotionSequenceRequest();
        }

        public GetMotionSequenceRequest(MotionSequenceRequest request)
        {
            this.request = request;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(request.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.request.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetMotionSequenceRequest: " +
            "\nrequest: " + request.ToString();
        }
    }
}
