//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPlannerParamsRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPlannerParams";

        //  Name of planning config
        public string planner_config;
        //  Optional name of planning group (return global defaults if empty)
        public string group;

        public GetPlannerParamsRequest()
        {
            this.planner_config = "";
            this.group = "";
        }

        public GetPlannerParamsRequest(string planner_config, string group)
        {
            this.planner_config = planner_config;
            this.group = group;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.planner_config));
            listOfSerializations.Add(SerializeString(this.group));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var planner_configStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.planner_config = DeserializeString(data, offset, planner_configStringBytesLength);
            offset += planner_configStringBytesLength;
            var groupStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.group = DeserializeString(data, offset, groupStringBytesLength);
            offset += groupStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "GetPlannerParamsRequest: " +
            "\nplanner_config: " + planner_config.ToString() +
            "\ngroup: " + group.ToString();
        }
    }
}
