//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPlanningSceneResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPlanningScene";

        public PlanningScene scene;

        public GetPlanningSceneResponse()
        {
            this.scene = new PlanningScene();
        }

        public GetPlanningSceneResponse(PlanningScene scene)
        {
            this.scene = scene;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(scene.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.scene.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPlanningSceneResponse: " +
            "\nscene: " + scene.ToString();
        }
    }
}
