//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPositionIKResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPositionIK";

        //  The returned solution 
        //  (in the same order as the list of joints specified in the IKRequest message)
        public RobotState solution;
        public MoveItErrorCodes error_code;

        public GetPositionIKResponse()
        {
            this.solution = new RobotState();
            this.error_code = new MoveItErrorCodes();
        }

        public GetPositionIKResponse(RobotState solution, MoveItErrorCodes error_code)
        {
            this.solution = solution;
            this.error_code = error_code;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(solution.SerializationStatements());
            listOfSerializations.AddRange(error_code.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.solution.Deserialize(data, offset);
            offset = this.error_code.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPositionIKResponse: " +
            "\nsolution: " + solution.ToString() +
            "\nerror_code: " + error_code.ToString();
        }
    }
}
