//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPlannerParamsResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPlannerParams";

        //  parameters as key-value pairs
        public PlannerParams @params;

        public GetPlannerParamsResponse()
        {
            this.@params = new PlannerParams();
        }

        public GetPlannerParamsResponse(PlannerParams @params)
        {
            this.@params = @params;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(@params.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.@params.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPlannerParamsResponse: " +
            "\n@params: " + @params.ToString();
        }
    }
}
