//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPlanningSceneRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPlanningScene";

        //  Get parts of the planning scene that are of interest
        //  All scene components are returned if none are specified
        public PlanningSceneComponents components;

        public GetPlanningSceneRequest()
        {
            this.components = new PlanningSceneComponents();
        }

        public GetPlanningSceneRequest(PlanningSceneComponents components)
        {
            this.components = components;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(components.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.components.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPlanningSceneRequest: " +
            "\ncomponents: " + components.ToString();
        }
    }
}
