//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPositionFKResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPositionFK";

        //  The resultant vector of PoseStamped messages that contains the (stamped) poses of the requested links
        public Geometry.PoseStamped[] pose_stamped;
        //  The list of link names corresponding to the poses
        public string[] fk_link_names;
        public MoveItErrorCodes error_code;

        public GetPositionFKResponse()
        {
            this.pose_stamped = new Geometry.PoseStamped[0];
            this.fk_link_names = new string[0];
            this.error_code = new MoveItErrorCodes();
        }

        public GetPositionFKResponse(Geometry.PoseStamped[] pose_stamped, string[] fk_link_names, MoveItErrorCodes error_code)
        {
            this.pose_stamped = pose_stamped;
            this.fk_link_names = fk_link_names;
            this.error_code = error_code;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(pose_stamped.Length));
            foreach(var entry in pose_stamped)
                listOfSerializations.Add(entry.Serialize());
            
            listOfSerializations.Add(BitConverter.GetBytes(fk_link_names.Length));
            foreach(var entry in fk_link_names)
                listOfSerializations.Add(SerializeString(entry));
            listOfSerializations.AddRange(error_code.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var pose_stampedArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.pose_stamped= new Geometry.PoseStamped[pose_stampedArrayLength];
            for(var i = 0; i < pose_stampedArrayLength; i++)
            {
                this.pose_stamped[i] = new Geometry.PoseStamped();
                offset = this.pose_stamped[i].Deserialize(data, offset);
            }
            
            var fk_link_namesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.fk_link_names= new string[fk_link_namesArrayLength];
            for(var i = 0; i < fk_link_namesArrayLength; i++)
            {
                var fk_link_namesStringBytesLength = DeserializeLength(data, offset);
                offset += 4;
                this.fk_link_names[i] = DeserializeString(data, offset, fk_link_namesStringBytesLength);
                offset += fk_link_namesStringBytesLength;
            }
            offset = this.error_code.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPositionFKResponse: " +
            "\npose_stamped: " + System.String.Join(", ", pose_stamped.ToList()) +
            "\nfk_link_names: " + System.String.Join(", ", fk_link_names.ToList()) +
            "\nerror_code: " + error_code.ToString();
        }
    }
}
