//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetPositionIKRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetPositionIK";

        //  A service call to carry out an inverse kinematics computation
        //  The inverse kinematics request
        public PositionIKRequest ik_request;

        public GetPositionIKRequest()
        {
            this.ik_request = new PositionIKRequest();
        }

        public GetPositionIKRequest(PositionIKRequest ik_request)
        {
            this.ik_request = ik_request;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(ik_request.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.ik_request.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetPositionIKRequest: " +
            "\nik_request: " + ik_request.ToString();
        }
    }
}
