//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetRobotStateFromWarehouseRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetRobotStateFromWarehouse";

        public string name;
        public string robot;

        public GetRobotStateFromWarehouseRequest()
        {
            this.name = "";
            this.robot = "";
        }

        public GetRobotStateFromWarehouseRequest(string name, string robot)
        {
            this.name = name;
            this.robot = robot;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            listOfSerializations.Add(SerializeString(this.robot));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            var robotStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.robot = DeserializeString(data, offset, robotStringBytesLength);
            offset += robotStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "GetRobotStateFromWarehouseRequest: " +
            "\nname: " + name.ToString() +
            "\nrobot: " + robot.ToString();
        }
    }
}
