//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetRobotStateFromWarehouseResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GetRobotStateFromWarehouse";

        public RobotState state;

        public GetRobotStateFromWarehouseResponse()
        {
            this.state = new RobotState();
        }

        public GetRobotStateFromWarehouseResponse(RobotState state)
        {
            this.state = state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(state.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.state.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetRobotStateFromWarehouseResponse: " +
            "\nstate: " + state.ToString();
        }
    }
}
