//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GetStateValidityRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/GetStateValidity";

        public RobotState robot_state;
        public string group_name;
        public Constraints constraints;

        public GetStateValidityRequest()
        {
            this.robot_state = new RobotState();
            this.group_name = "";
            this.constraints = new Constraints();
        }

        public GetStateValidityRequest(RobotState robot_state, string group_name, Constraints constraints)
        {
            this.robot_state = robot_state;
            this.group_name = group_name;
            this.constraints = constraints;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(robot_state.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.group_name));
            listOfSerializations.AddRange(constraints.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.robot_state.Deserialize(data, offset);
            var group_nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.group_name = DeserializeString(data, offset, group_nameStringBytesLength);
            offset += group_nameStringBytesLength;
            offset = this.constraints.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GetStateValidityRequest: " +
            "\nrobot_state: " + robot_state.ToString() +
            "\ngroup_name: " + group_name.ToString() +
            "\nconstraints: " + constraints.ToString();
        }
    }
}
