//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class GraspPlanningResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/GraspPlanning";

        //  the list of planned grasps
        public Grasp[] grasps;
        //  whether an error occurred
        public MoveItErrorCodes error_code;

        public GraspPlanningResponse()
        {
            this.grasps = new Grasp[0];
            this.error_code = new MoveItErrorCodes();
        }

        public GraspPlanningResponse(Grasp[] grasps, MoveItErrorCodes error_code)
        {
            this.grasps = grasps;
            this.error_code = error_code;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(grasps.Length));
            foreach(var entry in grasps)
                listOfSerializations.Add(entry.Serialize());
            listOfSerializations.AddRange(error_code.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var graspsArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.grasps= new Grasp[graspsArrayLength];
            for(var i = 0; i < graspsArrayLength; i++)
            {
                this.grasps[i] = new Grasp();
                offset = this.grasps[i].Deserialize(data, offset);
            }
            offset = this.error_code.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "GraspPlanningResponse: " +
            "\ngrasps: " + System.String.Join(", ", grasps.ToList()) +
            "\nerror_code: " + error_code.ToString();
        }
    }
}
