//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class ListRobotStatesInWarehouseRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/ListRobotStatesInWarehouse";

        public string regex;
        public string robot;

        public ListRobotStatesInWarehouseRequest()
        {
            this.regex = "";
            this.robot = "";
        }

        public ListRobotStatesInWarehouseRequest(string regex, string robot)
        {
            this.regex = regex;
            this.robot = robot;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.regex));
            listOfSerializations.Add(SerializeString(this.robot));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var regexStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.regex = DeserializeString(data, offset, regexStringBytesLength);
            offset += regexStringBytesLength;
            var robotStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.robot = DeserializeString(data, offset, robotStringBytesLength);
            offset += robotStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "ListRobotStatesInWarehouseRequest: " +
            "\nregex: " + regex.ToString() +
            "\nrobot: " + robot.ToString();
        }
    }
}
