//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class ListRobotStatesInWarehouseResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/ListRobotStatesInWarehouse";

        public string[] states;

        public ListRobotStatesInWarehouseResponse()
        {
            this.states = new string[0];
        }

        public ListRobotStatesInWarehouseResponse(string[] states)
        {
            this.states = states;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(states.Length));
            foreach(var entry in states)
                listOfSerializations.Add(SerializeString(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var statesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.states= new string[statesArrayLength];
            for(var i = 0; i < statesArrayLength; i++)
            {
                var statesStringBytesLength = DeserializeLength(data, offset);
                offset += 4;
                this.states[i] = DeserializeString(data, offset, statesStringBytesLength);
                offset += statesStringBytesLength;
            }

            return offset;
        }

        public override string ToString()
        {
            return "ListRobotStatesInWarehouseResponse: " +
            "\nstates: " + System.String.Join(", ", states.ToList());
        }
    }
}
