//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class LoadMapRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/LoadMap";

        public string filename;

        public LoadMapRequest()
        {
            this.filename = "";
        }

        public LoadMapRequest(string filename)
        {
            this.filename = filename;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.filename));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var filenameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.filename = DeserializeString(data, offset, filenameStringBytesLength);
            offset += filenameStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "LoadMapRequest: " +
            "\nfilename: " + filename.ToString();
        }
    }
}
