//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class QueryPlannerInterfacesRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/QueryPlannerInterfaces";


        public QueryPlannerInterfacesRequest()
        {
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {

            return offset;
        }

        public override string ToString()
        {
            return "QueryPlannerInterfacesRequest: ";
        }
    }
}
