//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class RenameRobotStateInWarehouseRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/RenameRobotStateInWarehouse";

        public string old_name;
        public string new_name;
        public string robot;

        public RenameRobotStateInWarehouseRequest()
        {
            this.old_name = "";
            this.new_name = "";
            this.robot = "";
        }

        public RenameRobotStateInWarehouseRequest(string old_name, string new_name, string robot)
        {
            this.old_name = old_name;
            this.new_name = new_name;
            this.robot = robot;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.old_name));
            listOfSerializations.Add(SerializeString(this.new_name));
            listOfSerializations.Add(SerializeString(this.robot));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var old_nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.old_name = DeserializeString(data, offset, old_nameStringBytesLength);
            offset += old_nameStringBytesLength;
            var new_nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.new_name = DeserializeString(data, offset, new_nameStringBytesLength);
            offset += new_nameStringBytesLength;
            var robotStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.robot = DeserializeString(data, offset, robotStringBytesLength);
            offset += robotStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "RenameRobotStateInWarehouseRequest: " +
            "\nold_name: " + old_name.ToString() +
            "\nnew_name: " + new_name.ToString() +
            "\nrobot: " + robot.ToString();
        }
    }
}
