//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class SaveRobotStateToWarehouseRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/SaveRobotStateToWarehouse";

        public string name;
        public string robot;
        public RobotState state;

        public SaveRobotStateToWarehouseRequest()
        {
            this.name = "";
            this.robot = "";
            this.state = new RobotState();
        }

        public SaveRobotStateToWarehouseRequest(string name, string robot, RobotState state)
        {
            this.name = name;
            this.robot = robot;
            this.state = state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.name));
            listOfSerializations.Add(SerializeString(this.robot));
            listOfSerializations.AddRange(state.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var nameStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.name = DeserializeString(data, offset, nameStringBytesLength);
            offset += nameStringBytesLength;
            var robotStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.robot = DeserializeString(data, offset, robotStringBytesLength);
            offset += robotStringBytesLength;
            offset = this.state.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "SaveRobotStateToWarehouseRequest: " +
            "\nname: " + name.ToString() +
            "\nrobot: " + robot.ToString() +
            "\nstate: " + state.ToString();
        }
    }
}
