//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class UpdatePointcloudOctomapResponse : Message
    {
        public const string RosMessageName = "moveit_msgs/UpdatePointcloudOctomap";

        public bool success;

        public UpdatePointcloudOctomapResponse()
        {
            this.success = false;
        }

        public UpdatePointcloudOctomapResponse(bool success)
        {
            this.success = success;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.success));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.success = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

        public override string ToString()
        {
            return "UpdatePointcloudOctomapResponse: " +
            "\nsuccess: " + success.ToString();
        }
    }
}
