//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class UpdatePointcloudOctomapRequest : Message
    {
        public const string RosMessageName = "moveit_msgs/UpdatePointcloudOctomap";

        public Sensor.PointCloud2 cloud;

        public UpdatePointcloudOctomapRequest()
        {
            this.cloud = new Sensor.PointCloud2();
        }

        public UpdatePointcloudOctomapRequest(Sensor.PointCloud2 cloud)
        {
            this.cloud = cloud;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(cloud.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.cloud.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "UpdatePointcloudOctomapRequest: " +
            "\ncloud: " + cloud.ToString();
        }
    }
}
