//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class CartesianPoint : Message
    {
        public const string RosMessageName = "moveit_msgs/CartesianPoint";

        //  This message defines a point in a cartesian trajectory
        public Geometry.Pose pose;
        public Geometry.Twist velocity;
        public Geometry.Accel acceleration;

        public CartesianPoint()
        {
            this.pose = new Geometry.Pose();
            this.velocity = new Geometry.Twist();
            this.acceleration = new Geometry.Accel();
        }

        public CartesianPoint(Geometry.Pose pose, Geometry.Twist velocity, Geometry.Accel acceleration)
        {
            this.pose = pose;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(pose.SerializationStatements());
            listOfSerializations.AddRange(velocity.SerializationStatements());
            listOfSerializations.AddRange(acceleration.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.pose.Deserialize(data, offset);
            offset = this.velocity.Deserialize(data, offset);
            offset = this.acceleration.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "CartesianPoint: " +
            "\npose: " + pose.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nacceleration: " + acceleration.ToString();
        }
    }
}
