//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class OrientedBoundingBox : Message
    {
        public const string RosMessageName = "moveit_msgs/OrientedBoundingBox";

        //  the pose of the box
        public Geometry.Pose pose;
        //  the extents of the box, assuming the center is at the origin
        public Geometry.Point32 extents;

        public OrientedBoundingBox()
        {
            this.pose = new Geometry.Pose();
            this.extents = new Geometry.Point32();
        }

        public OrientedBoundingBox(Geometry.Pose pose, Geometry.Point32 extents)
        {
            this.pose = pose;
            this.extents = extents;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(pose.SerializationStatements());
            listOfSerializations.AddRange(extents.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.pose.Deserialize(data, offset);
            offset = this.extents.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "OrientedBoundingBox: " +
            "\npose: " + pose.ToString() +
            "\nextents: " + extents.ToString();
        }
    }
}
