//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10EMoveitConfig
{
    public class UR10eJoints : Message
    {
        public const string RosMessageName = "ur10_e_moveit_config/UR10eJoints";

        public double joint_00;

        public UR10eJoints()
        {
            this.joint_00 = 0.0;
        }

        public UR10eJoints(double joint_00)
        {
            this.joint_00 = joint_00;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.joint_00));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.joint_00 = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "UR10eJoints: " +
            "\njoint_00: " + joint_00.ToString();
        }
    }
}
