//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class ExecuteTrajectoryResult : Message
    {
        public const string RosMessageName = "moveit_msgs/ExecuteTrajectory";

        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodes error_code;

        public ExecuteTrajectoryResult()
        {
            this.error_code = new MoveItErrorCodes();
        }

        public ExecuteTrajectoryResult(MoveItErrorCodes error_code)
        {
            this.error_code = error_code;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(error_code.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.error_code.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryResult: " +
            "\nerror_code: " + error_code.ToString();
        }
    }
}
