//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class ExecuteTrajectoryGoal : Message
    {
        public const string RosMessageName = "moveit_msgs/ExecuteTrajectory";

        //  The trajectory to execute
        public RobotTrajectory trajectory;

        public ExecuteTrajectoryGoal()
        {
            this.trajectory = new RobotTrajectory();
        }

        public ExecuteTrajectoryGoal(RobotTrajectory trajectory)
        {
            this.trajectory = trajectory;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(trajectory.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.trajectory.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryGoal: " +
            "\ntrajectory: " + trajectory.ToString();
        }
    }
}
