//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MoveGroupSequenceResult : Message
    {
        public const string RosMessageName = "moveit_msgs/MoveGroupSequence";

        //  Response comprising information on all sections of the sequence
        public MotionSequenceResponse response;

        public MoveGroupSequenceResult()
        {
            this.response = new MotionSequenceResponse();
        }

        public MoveGroupSequenceResult(MotionSequenceResponse response)
        {
            this.response = response;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(response.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.response.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MoveGroupSequenceResult: " +
            "\nresponse: " + response.ToString();
        }
    }
}
