//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class MoveGroupGoal : Message
    {
        public const string RosMessageName = "moveit_msgs/MoveGroup";

        //  Motion planning request to pass to planner
        public MotionPlanRequest request;
        //  Planning options
        public PlanningOptions planning_options;

        public MoveGroupGoal()
        {
            this.request = new MotionPlanRequest();
            this.planning_options = new PlanningOptions();
        }

        public MoveGroupGoal(MotionPlanRequest request, PlanningOptions planning_options)
        {
            this.request = request;
            this.planning_options = planning_options;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(request.SerializationStatements());
            listOfSerializations.AddRange(planning_options.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.request.Deserialize(data, offset);
            offset = this.planning_options.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "MoveGroupGoal: " +
            "\nrequest: " + request.ToString() +
            "\nplanning_options: " + planning_options.ToString();
        }
    }
}
