//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    public class PlaceFeedback : Message
    {
        public const string RosMessageName = "moveit_msgs/Place";

        //  The internal state that the place action currently is in
        public string state;

        public PlaceFeedback()
        {
            this.state = "";
        }

        public PlaceFeedback(string state)
        {
            this.state = state;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.state));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var stateStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.state = DeserializeString(data, offset, stateStringBytesLength);
            offset += stateStringBytesLength;

            return offset;
        }

        public override string ToString()
        {
            return "PlaceFeedback: " +
            "\nstate: " + state.ToString();
        }
    }
}
